version: 2
jobs:
        dawn:
                docker:
                        - image: gtclang/dawn-env-cuda10.1-ubuntu18.04
                steps:
                        - checkout:
                                  path: /usr/src/dawn
                        - run:
                                  name: Build and test
                                  command: |
                                          /usr/src/dawn/scripts/build-and-test \
                                          --dawn-install-dir /usr/local/dawn \
                                          --parallel $(nproc) \
                                          -DCMAKE_PREFIX_PATH=/usr/lib/llvm-9 \
                                          -DProtobuf_DIR=/usr/local/protobuf/lib/cmake/protobuf \
                                          -DPROTOBUF_PYTHON_DIR=/usr/local/lib/python3.7/dist-packages \
                                          -DGridTools_DIR=/usr/local/gridtools/lib/cmake \
                                          -Datlas_DIR=/usr/local/atlas/lib/cmake/atlas \
                                          -Deckit_DIR=/usr/local/eckit/lib/cmake/eckit \
                                          -GNinja
