version: 2
jobs:
        dawn:
                docker:
                        - image: gtclang/dawn-env-ubuntu19.10
                steps:
                        - checkout:
                                  path: /usr/src/dawn
                        - run:
                                  name: Build and test
                                  command: |
                                          /usr/src/dawn/scripts/build-and-test \
                                          --parallel $(nproc) \
                                          --install-dir /usr/local \
                                          -DCMAKE_PREFIX_PATH=/usr/lib/llvm-9 \
                                          -DGridTools_DIR=/usr/local/lib/cmake \
                                          -DPROTOBUF_PYTHON_DIR=/usr/local/lib/python3.7/dist-packages \
                                          -GNinja
